global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python-backend'
    # host.docker.internal permite que o container acesse o localhost da sua máquina
    static_configs:
      - targets: ['host.docker.internal:8000']